# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import lambda_cloud_client
from lambda_cloud_client.models.region import Region  # noqa: E501
from lambda_cloud_client.rest import ApiException

class TestRegion(unittest.TestCase):
    """Region unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Region
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Region`
        """
        model = lambda_cloud_client.models.region.Region()  # noqa: E501
        if include_optional :
            return Region(
                name = 'us-tx-1', 
                description = 'Austin, Texas'
            )
        else :
            return Region(
                name = 'us-tx-1',
                description = 'Austin, Texas',
        )
        """

    def testRegion(self):
        """Test Region"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
