# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import lambda_cloud_client
from lambda_cloud_client.models.error_code import ErrorCode  # noqa: E501
from lambda_cloud_client.rest import ApiException

class TestErrorCode(unittest.TestCase):
    """ErrorCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorCode(self):
        """Test ErrorCode"""
        # inst = ErrorCode()

if __name__ == '__main__':
    unittest.main()
