# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import lambda_cloud_client
from lambda_cloud_client.api.default_api import DefaultApi  # noqa: E501
from lambda_cloud_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = lambda_cloud_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_ssh_key(self):
        """Test case for add_ssh_key

        Add SSH key  # noqa: E501
        """
        pass

    def test_delete_ssh_key(self):
        """Test case for delete_ssh_key

        Delete SSH key  # noqa: E501
        """
        pass

    def test_get_instance(self):
        """Test case for get_instance

        List details of a specific instance  # noqa: E501
        """
        pass

    def test_instance_types(self):
        """Test case for instance_types

        Retrieve list of offered instance types  # noqa: E501
        """
        pass

    def test_launch_instance(self):
        """Test case for launch_instance

        Launch instances  # noqa: E501
        """
        pass

    def test_list_file_systems(self):
        """Test case for list_file_systems

        List file systems  # noqa: E501
        """
        pass

    def test_list_instances(self):
        """Test case for list_instances

        List running instances  # noqa: E501
        """
        pass

    def test_list_ssh_keys(self):
        """Test case for list_ssh_keys

        List SSH keys  # noqa: E501
        """
        pass

    def test_restart_instance(self):
        """Test case for restart_instance

        Restart instances  # noqa: E501
        """
        pass

    def test_terminate_instance(self):
        """Test case for terminate_instance

        Terminate an instance  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
