# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import lambda_cloud_client
from lambda_cloud_client.models.error_response_body import ErrorResponseBody  # noqa: E501
from lambda_cloud_client.rest import ApiException

class TestErrorResponseBody(unittest.TestCase):
    """ErrorResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ErrorResponseBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ErrorResponseBody`
        """
        model = lambda_cloud_client.models.error_response_body.ErrorResponseBody()  # noqa: E501
        if include_optional :
            return ErrorResponseBody(
                error = lambda_cloud_client.models.error.error(
                    code = 'global/unknown', 
                    message = 'API key is invalid, expired, or deleted.', 
                    suggestion = 'Create a new API key and try again.', ), 
                field_errors = {
                    'key' : lambda_cloud_client.models.error.error(
                        code = 'global/unknown', 
                        message = 'API key is invalid, expired, or deleted.', 
                        suggestion = 'Create a new API key and try again.', )
                    }
            )
        else :
            return ErrorResponseBody(
                error = lambda_cloud_client.models.error.error(
                    code = 'global/unknown', 
                    message = 'API key is invalid, expired, or deleted.', 
                    suggestion = 'Create a new API key and try again.', ),
        )
        """

    def testErrorResponseBody(self):
        """Test ErrorResponseBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
